[profile.default]
src = "contracts"
out = "out"
libs = ["node_modules", "lib"]
test = 'test/foundry'
remappings = [
    "@openzeppelin/=node_modules/@openzeppelin/",
    "eth-gas-reporter/=node_modules/eth-gas-reporter/",
    "hardhat/=node_modules/hardhat/",
    "ds-test/=lib/forge-std/lib/ds-test/src/",
    "forge-std/=lib/forge-std/src/"
]
cache_path = 'forge-cache'
# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
